# Generated by Django 3.0.5 on 2020-04-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_description', models.TextField()),
                ('book_availibility', models.CharField(choices=[('T', 'True'), ('F', 'False')], default='T', max_length=1)),
                ('book_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('book_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Owner')),
            ],
        ),
    ]
