# Generated by Django 3.0.5 on 2020-04-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200411_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_availibility',
            field=models.CharField(choices=[('Availible', 'Availible'), ('Not_availible', 'Not availible')], default='Availible', max_length=20),
        ),
    ]
